name: 'Github Push Bot'

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with: { ref: main }
      - name: 'Run code push message'
        run: git clone https://github.com/x-cmd/nightly.git && cd nightly && ls
